import * as dotenv from "dotenv";
dotenv.config();

const CONVEX_HTTP_URL = process.env.CONVEX_HTTP_URL;

if (!CONVEX_HTTP_URL) {

  console.error("CONVEX_HTTP_URL not set");
  process.exit(1);
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const BRAND_GROUPS: { officialName: string; synonyms: string[] }[] = [
  { officialName: "210", synonyms: [] },
  { officialName: "224", synonyms: [] },
  { officialName: "Acacia", synonyms: [] },
  { officialName: "Ace", synonyms: [] },
  { officialName: "Ariel", synonyms: [] },
  { officialName: "Aquamist", synonyms: ["Aqua Mist", "Aqua-Mist"] },
  { officialName: "Aquafresh", synonyms: ["Aqua Fresh", "Aqua-Fresh"] },
  { officialName: "Exe", synonyms: [] },
  { officialName: "Festive", synonyms: [] },
  { officialName: "Santa Maria", synonyms: ["Santamaria", "Santa-Maria"] },
  { officialName: "Golden Fry", synonyms: ["GoldenFry", "Golden-Fry"] },
  { officialName: "Ajab", synonyms: [] },
  { officialName: "Dove", synonyms: [] },
  { officialName: "Downy", synonyms: [] },
  { officialName: "Pendo", synonyms: [] },
  { officialName: "Pepsi", synonyms: [] },
  { officialName: "Pembe", synonyms: [] },
  { officialName: "Persil", synonyms: [] },
  { officialName: "Pepsodent", synonyms: [] },
  { officialName: "Peptang", synonyms: [] },
  { officialName: "Pick N Peel", synonyms: ["Pick-N-Peel", "PickNPeel", "Pick and Peel"] },
  { officialName: "Santa Lucia", synonyms: ["Santalucia", "Santa-Lucia"] },
  { officialName: "Pride", synonyms: [] },
  { officialName: "Fresh Fri", synonyms: ["FreshFri", "Fresh-Fri"] },
  { officialName: "Pringles", synonyms: [] },
  { officialName: "Nestle", synonyms: ["Nestlé"] },
  { officialName: "Blue Band", synonyms: ["Blueband", "Blue-Band", "BlueBand"] },
  { officialName: "Parle G", synonyms: ["Parle-G", "ParleG", "Parle Glucose", "Parle-Glucose"] },
  { officialName: "Baraka Chai", synonyms: ["Baraka-Chai", "BarakaChai", "Baraka Tea"] },
  { officialName: "Tap & Go", synonyms: ["Tap and Go", "Tap&Go", "Tap Go"] },
  { officialName: "Naivas Local", synonyms: ["Naivas"] },
  { officialName: "Quick Choice", synonyms: ["QuickChoice", "Quick-Choice", "Quickchoice"] },
  { officialName: "Mill Bakers", synonyms: ["Millbakers", "Mill-Bakers"] },
  { officialName: "Majid Al Futtaim", synonyms: ["Majid Al-Futtaim", "MAF"] },
  { officialName: "Brookside", synonyms: ["Brook Side", "Brook-Side"] },
  { officialName: "Kenchic", synonyms: ["Kenchick", "Ken Chic", "Ken-Chic"] },
  { officialName: "Avena", synonyms: [] },
  { officialName: "Tuzo", synonyms: [] },
  { officialName: "Lotus", synonyms: [] },
  { officialName: "Lucozade", synonyms: ["Lucoazade", "Lucozaid"] },
  { officialName: "KCC", synonyms: ["K.C.C", "K.C.C.", "Kenya Cooperative Creameries"] },
  { officialName: "Mt Kenya", synonyms: ["Mount Kenya", "Mt. Kenya", "MtKenya"] },
  { officialName: "Broadways", synonyms: ["Broadway", "Broadway's"] },
  { officialName: "Supaloaf", synonyms: ["Supa Loaf", "Supa-Loaf"] },
  { officialName: "Supabrite", synonyms: ["Supa Brite", "Supa-Brite", "Supabright", "Supa Bright"] },
  { officialName: "Sunlight", synonyms: ["Sun Light", "Sun-Light"] },
  { officialName: "Sunrice", synonyms: ["Sun Rice", "Sun-Rice"] },
  { officialName: "Neptune", synonyms: [] },
  { officialName: "Ndume", synonyms: [] },
  { officialName: "Ndovu", synonyms: [] },
  { officialName: "Ndhiwa", synonyms: [] },
  { officialName: "Nature's Own", synonyms: ["Natures Own", "NaturesOwn", "Natures-Own"] },
  { officialName: "Nice Lovely", synonyms: ["NiceLovely", "Nice-Lovely"] },
  { officialName: "Nice Soft", synonyms: ["NiceSoft", "Nice-Soft"] },
  { officialName: "Nice", synonyms: [] },
  { officialName: "Novida", synonyms: [] },
  { officialName: "Nuteez", synonyms: ["Nut-eez", "Nut Eez"] },
  { officialName: "Nut Gold", synonyms: ["NutGold", "Nut-Gold"] },
  { officialName: "Nuvita", synonyms: [] },
  { officialName: "Pampers", synonyms: [] },
  { officialName: "Panadol", synonyms: [] },
  { officialName: "Dola", synonyms: [] },
  { officialName: "Fresha", synonyms: [] },
  { officialName: "Quencher", synonyms: [] },
  { officialName: "Rinsun", synonyms: ["Rin Sun", "Rin-Sun"] },
  { officialName: "Kimbo", synonyms: [] },
  { officialName: "Cowboy", synonyms: [] },
  { officialName: "Sun Gold", synonyms: ["SunGold", "Sun-Gold"] },
  { officialName: "Kentaste", synonyms: ["Ken Taste", "Ken-Taste"] },
  { officialName: "Chipsy", synonyms: ["Chipsi"] },
  { officialName: "Bio", synonyms: [] },
  { officialName: "Nutrameal", synonyms: ["Nutra Meal", "Nutra-Meal"] },
  { officialName: "Soko", synonyms: [] },
  { officialName: "Pearl", synonyms: [] },
  { officialName: "Ranee", synonyms: [] },
  { officialName: "Guru", synonyms: [] },
  { officialName: "Guru Premium", synonyms: ["GuruPremium", "Guru-Premium"] },
  { officialName: "KPL", synonyms: ["K.P.L", "K.P.L."] },
  { officialName: "Tily", synonyms: [] },
  { officialName: "Kasuku", synonyms: [] },
  { officialName: "Morning Fresh", synonyms: ["MorningFresh", "Morning-Fresh"] },
  { officialName: "Jogoo", synonyms: [] },
  { officialName: "Hostess", synonyms: [] },
  { officialName: "Huggies", synonyms: [] },
  { officialName: "Fahari", synonyms: [] },
  { officialName: "Hanan", synonyms: [] },
  { officialName: "Jamaa", synonyms: [] },
  { officialName: "Rina", synonyms: [] },
  { officialName: "Indomie", synonyms: ["Indo Mie", "Indo-Mie"] },
  { officialName: "Kabras", synonyms: [] },
  { officialName: "Kensalt", synonyms: ["Ken Salt", "Ken-Salt"] },
  { officialName: "Mumias", synonyms: [] },
  { officialName: "Daima", synonyms: [] },
  { officialName: "Dairy Land", synonyms: ["DairyLand", "Dairy-Land"] },
  { officialName: "Daawat", synonyms: ["Dawat", "Da'awat"] },
  { officialName: "Dasani", synonyms: [] },
  { officialName: "Dettol", synonyms: [] },
  { officialName: "Molo", synonyms: [] },
  { officialName: "Molfix", synonyms: ["Mol Fix", "Mol-Fix"] },
  { officialName: "Ilara", synonyms: [] },
  { officialName: "Delamere", synonyms: ["De La Mere", "De-Lamere"] },
  { officialName: "Zesta", synonyms: [] },
  { officialName: "Baraka", synonyms: [] },
  { officialName: "Top Fry", synonyms: ["TopFry", "Top-Fry"] },
  { officialName: "Olive Gold", synonyms: ["OliveGold", "Olive-Gold"] },
  { officialName: "Prestige", synonyms: [] },
  { officialName: "Weetabix", synonyms: [] },
  { officialName: "Kericho Gold", synonyms: ["KerichoGold", "Kericho-Gold", "Kericho"] },
  { officialName: "Shiriki Coffee", synonyms: ["Shiriki", "Shiriki-Coffee"] },
  { officialName: "Milo", synonyms: [] },
  { officialName: "MacCoffee", synonyms: ["Maccoffee", "Mac Coffee", "Mac-Coffee"] },
  { officialName: "Faraja", synonyms: [] },
  { officialName: "Softcare", synonyms: ["Soft Care", "Soft-Care"] },
  { officialName: "Kotex", synonyms: [] },
  { officialName: "Molped", synonyms: [] },
  { officialName: "Velvex", synonyms: [] },
  { officialName: "Velvex Extra", synonyms: ["VelvexExtra", "Velvex-Extra"] },
  { officialName: "Tena", synonyms: [] },
  { officialName: "Fay", synonyms: [] },
  { officialName: "Toilex", synonyms: [] },
  { officialName: "Flora", synonyms: [] },
  { officialName: "Petals", synonyms: [] },
  { officialName: "Rosy", synonyms: [] },
  { officialName: "Celine", synonyms: [] },
  { officialName: "Sifa", synonyms: [] },
  { officialName: "Comfy", synonyms: [] },
  { officialName: "Cosy", synonyms: ["Cozy"] },
  { officialName: "Msafi", synonyms: [] },
  { officialName: "Omo", synonyms: [] },
  { officialName: "Toss", synonyms: [] },
  { officialName: "Unilever", synonyms: [] },
  { officialName: "Geisha", synonyms: [] },
  { officialName: "Colgate", synonyms: [] },
  { officialName: "Close Up", synonyms: ["CloseUp", "Close-Up"] },
  { officialName: "Lifebuoy", synonyms: ["Lifebouy", "Life Buoy", "Life-Buoy", "Lifeboy"] },
  { officialName: "Vaseline", synonyms: [] },
  { officialName: "Royco", synonyms: [] },
  { officialName: "Tropical Heat", synonyms: ["TropicalHeat", "Tropical-Heat"] },
  { officialName: "Menengai", synonyms: [] },
  { officialName: "Zenta", synonyms: [] },
  { officialName: "Whitewash", synonyms: ["White Wash", "White-Wash"] },
  { officialName: "Usindi", synonyms: [] },
  { officialName: "Umix", synonyms: [] },
  { officialName: "Spenza", synonyms: [] },
  { officialName: "Butterfly", synonyms: [] },
  { officialName: "Joymax", synonyms: ["Joy Max", "Joy-Max"] },
  { officialName: "Highlands", synonyms: [] },
  { officialName: "Amaize", synonyms: ["A-Maize", "AMaize"] },
  { officialName: "CIL", synonyms: ["C.I.L", "C.I.L."] },
  { officialName: "Nala", synonyms: [] },
  { officialName: "Coca-Cola", synonyms: ["Cocacola", "Coca Cola", "Coke"] },
  { officialName: "Famila", synonyms: [] },
  { officialName: "Raha", synonyms: [] },
  { officialName: "Cadbury", synonyms: [] },
];

const WORD_GROUPS: { officialName: string; synonyms: string[] }[] = [
{ officialName: "flour", synonyms: ["meal", "unga", "floor"] },
{ officialName: "maize flour", synonyms: ["maize meal", "ugali flour", "posho", "corn flour", "cornflour"] },
{ officialName: "corn flour", synonyms: [ "corn flour", "cornflour"] },
{ officialName: "wheat flour", synonyms: ["ngano", "all purpose flour", "all-purpose flour", "plain flour", "home baking", "homebaking", "chapati flour"] },
{ officialName: "self raising flour", synonyms: ["self-raising flour", "self rising flour", "s/raising", "SR flour"] },
{ officialName: "semolina", synonyms: ["semolina flour", "cream of wheat"] },
{ officialName: "rice", synonyms: ["wali", "mchele", "basmati", "jasmine rice", "long grain", "short grain"] },
{ officialName: "pasta", synonyms: ["noodles", "macaroni", "spaghetti", "penne", "spirali", "spirals", "fusilli", "linguine", "rigatoni"] },
{ officialName: "macaroni", synonyms: ["mac", "mac n cheese", "macaroni cheese"] },
{ officialName: "spaghetti", synonyms: ["spag", "sphagetti", "spagetti"] },
{ officialName: "bread", synonyms: ["mkate", "loaf", "sliced bread", "white bread", "brown bread", "wholemeal bread", "wholewheat bread"] },
{ officialName: "chapati", synonyms: ["chap", "chapati flour", "roti"] },
{ officialName: "sugar", synonyms: ["sukari", "sukari nguuru", "brown sugar", "white sugar", "caster sugar", "icing sugar", "granulated sugar"] },
{ officialName: "salt", synonyms: ["chumvi", "table salt", "iodised salt", "iodized salt", "sea salt", "rock salt"] },
{ officialName: "cooking oil", synonyms: ["mafuta", "vegetable oil", "veg oil", "sunflower oil", "corn oil", "canola oil", "palm oil", "frying oil"] },
{ officialName: "olive oil", synonyms: ["oliveoil", "olive-oil", "olives oil"] },
{ officialName: "extra virgin", synonyms: ["e/virgin", "extra-virgin", "ev", "evoo", "extra virgin olive oil", "e.v.o.o"] },
{ officialName: "butter", synonyms: ["siagi", "bata", "margarine", "spread", "cooking butter"] },
{ officialName: "margarine", synonyms: ["marg", "spread", "baking margarine"] },
{ officialName: "honey", synonyms: ["asali", "pure honey", "raw honey", "natural honey"] },
{ officialName: "jam", synonyms: ["jamu", "fruit jam", "strawberry jam", "marmalade", "preserve"] },
{ officialName: "peanut butter", synonyms: ["groundnut paste", "groundnut butter", "peanutbutter", "p/butter", "pb"] },
{ officialName: "tomato paste", synonyms: ["tomato puree", "tomato sauce", "tomato concentrate", "t/paste", "nyanya paste"] },
{ officialName: "ketchup", synonyms: ["tomato ketchup", "tomato sauce", "catsup", "tomato relish"] },
{ officialName: "mayonnaise", synonyms: ["mayo", "mayonaise", "mayyonaise", "salad cream"] },
{ officialName: "vinegar", synonyms: ["white vinegar", "malt vinegar", "spirit vinegar"] },
{ officialName: "soy sauce", synonyms: ["soya sauce", "soysauce", "soyasauce"] },
{ officialName: "hot sauce", synonyms: ["chilli sauce", "pepper sauce", "pili pili sauce"] },
{ officialName: "baking powder", synonyms: ["b/powder", "b.p.", "leavening", "raising agent"] },
{ officialName: "baking soda", synonyms: ["bicarbonate of soda", "bicarb", "bicarbonate", "soda"] },
{ officialName: "yeast", synonyms: ["instant yeast", "dry yeast", "active yeast"] },
{ officialName: "vanilla", synonyms: ["vanilla essence", "vanilla extract", "vanilla flavor", "vanilla flavour"] },
{ officialName: "cinnamon", synonyms: ["dalasini"] },
{ officialName: "turmeric", synonyms: ["manjano", "tumeric"] },
{ officialName: "pepper", synonyms: ["pilipili", "black pepper", "white pepper", "peppercorn", "pilipili manga"] },
{ officialName: "chilli", synonyms: ["chili", "chile", "pili pili", "piri piri", "pilipili hoho", "cayenne"] },
{ officialName: "garlic", synonyms: ["kitunguu saumu", "garlic paste", "garlic powder", "minced garlic"] },
{ officialName: "ginger", synonyms: ["tangawizi", "ginger paste", "ground ginger"] },
{ officialName: "onion", synonyms: ["kitunguu", "onion powder", "onion flakes"] },
{ officialName: "noodles", synonyms: ["instant noodles", "ramen", "cup noodles", "noodels"] },
{ officialName: "cereal", synonyms: ["breakfast cereal", "corn flakes", "cornflakes", "porridge", "oats", "oatmeal"] },
{ officialName: "oats", synonyms: ["oatmeal", "rolled oats", "instant oats", "porridge oats"] },
{ officialName: "cornflakes", synonyms: ["corn flakes", "corn-flakes"] },
{ officialName: "muesli", synonyms: ["granola", "muesli mix"] },
{ officialName: "biscuits", synonyms: ["cookies", "biskits", "biscits", "crackers", "digestive"] },
{ officialName: "snacks", synonyms: ["crisps", "chips", "popcorn"] },
{ officialName: "crisps", synonyms: ["chips", "potato chips", "potato crisps"] },
{ officialName: "chocolate", synonyms: ["choc", "choco", "dark chocolate", "milk chocolate", "chocolat"] },
{ officialName: "sweets", synonyms: ["candy", "lollipop", "toffee", "chewing gum", "gum", "confectionery"] },
{ officialName: "groundnuts", synonyms: ["njugu", "peanuts", "njugu karanga", "roasted peanuts"] },
{ officialName: "beans", synonyms: ["maharagwe", "kidney beans", "mixed beans", "dry beans"] },
{ officialName: "lentils", synonyms: ["dengu", "green grams", "green gram", "ndengu"] },
{ officialName: "chickpeas", synonyms: ["garbanzo", "dengu kubwa"] },
{ officialName: "canned tomatoes", synonyms: ["tinned tomatoes", "chopped tomatoes", "whole tomatoes"] },
{ officialName: "canned beans", synonyms: ["tinned beans", "baked beans"] },
{ officialName: "stock", synonyms: ["stock cube", "bouillon", "broth", "beef stock", "chicken stock", "stock cubes"] },
{ officialName: "coconut milk", synonyms: ["maziwa ya nazi", "coconut cream", "canned coconut"] },
{ officialName: "custard", synonyms: ["custard powder", "vanilla custard"] },
{ officialName: "jelly", synonyms: ["jello", "gelatin", "jelly powder"] },
{ officialName: "ice cream", synonyms: ["icecream", "ice-cream", "gelato", "frozen dessert"] },
{ officialName: "water", synonyms: ["maji", "drinking water", "mineral water", "still water", "sparkling water", "bottled water"] },
{ officialName: "juice", synonyms: ["fruit juice", "fresh juice", "100% juice", "nectar", "juice drink"] },
{ officialName: "soft drink", synonyms: ["soda", "fizzy drink", "carbonated drink", "cold drink", "coke", "cola", "pop"] },
{ officialName: "energy drink", synonyms: ["energy", "power drink", "sports drink"] },
{ officialName: "squash", synonyms: ["cordial", "juice concentrate", "dilutable juice", "dilute juice"] },
{ officialName: "coffee", synonyms: ["coffe", "cofee", "kahawa"] },
{ officialName: "instant coffee", synonyms: ["instantcoffee", "instantcoffe", "instantcofee", "coffee instant", "coffeinstant", "soluble coffee"] },
{ officialName: "tea", synonyms: ["chai", "black tea", "green tea", "herbal tea", "loose tea", "leaf tea"] },
{ officialName: "tea bag", synonyms: ["t/bag", "t/bags", "teabag", "teabags", "tea bags", "tea-bag", "tea-bags"] },
{ officialName: "milk", synonyms: ["maziwa", "full cream milk", "skimmed milk", "semi skimmed", "UHT milk", "long life milk", "fresh milk"] },
{ officialName: "milo", synonyms: ["cocoa", "hot chocolate", "drinking chocolate", "malt drink"] },
{ officialName: "beer", synonyms: ["bia", "lager", "ale", "stout", "larger"] },
{ officialName: "wine", synonyms: ["mvinyo", "red wine", "white wine", "rose wine", "rosé"] },
{ officialName: "spirit", synonyms: ["spirits", "whisky", "whiskey", "vodka", "gin", "rum", "brandy"] },
{ officialName: "yoghurt", synonyms: ["yogurt", "yoghourt", "youghurt", "yougurt", "maziwa lala"] },
{ officialName: "cheese", synonyms: ["jibini", "cheddar", "mozzarella", "processed cheese", "cheese slice", "cheese slices"] },
{ officialName: "cream", synonyms: ["whipping cream", "double cream", "single cream", "fresh cream", "sour cream"] },
{ officialName: "ghee", synonyms: ["samli", "clarified butter", "cooking ghee"] },
{ officialName: "eggs", synonyms: ["mayai", "egg", "tray of eggs", "half tray"] },
{ officialName: "condensed milk", synonyms: ["sweetened condensed milk", "cond milk", "c/milk"] },
{ officialName: "evaporated milk", synonyms: ["evap milk", "e/milk", "unsweetened milk", "carnation"] },
{ officialName: "powdered milk", synonyms: ["milk powder", "dry milk", "dried milk", "p/milk", "uji powder"] },
{ officialName: "beef", synonyms: ["nyama", "nyama ya ng'ombe", "mince", "minced beef", "ground beef", "steak", "brisket"] },
{ officialName: "chicken", synonyms: ["kuku", "poultry", "whole chicken", "chicken pieces", "chicken breast", "chicken thigh", "drumstick"] },
{ officialName: "pork", synonyms: ["nguruwe", "bacon", "sausage", "pork sausage"] },
{ officialName: "fish", synonyms: ["samaki", "tilapia", "omena", "dagaa", "tuna", "sardines", "canned fish"] },
{ officialName: "sausage", synonyms: ["sausages", "frank", "frankfurter", "hotdog", "wiener", "banger"] },
{ officialName: "mince", synonyms: ["minced meat", "ground meat", "mincemeat", "minced beef", "minced chicken"] },
{ officialName: "sachet", synonyms: ["packet", "pack", "pouch", "pkt", "pkts", "sachet pack"] },
{ officialName: "bottle", synonyms: ["btl", "btls", "bot", "bots", "glass bottle", "plastic bottle"] },
{ officialName: "tin", synonyms: ["can", "canned", "tinned", "tin can"] },
{ officialName: "bar", synonyms: ["block", "slab", "cake", "tablet"] },
{ officialName: "bag", synonyms: ["mfuko", "poly bag", "polybag", "sack"] },
{ officialName: "carton", synonyms: ["box", "ctn", "ctns", "tetra", "tetra pak", "tetrapak", "tetra pack"] },
{ officialName: "tube", synonyms: ["squeeze tube", "paste tube"] },
{ officialName: "jar", synonyms: ["glass jar", "tub", "pot"] },
{ officialName: "tray", synonyms: ["punnet", "blister pack"] },
{ officialName: "roll", synonyms: ["toilet roll", "kitchen roll", "roll pack"] },
{ officialName: "refill", synonyms: ["refill pack", "top up", "recharge", "r/fill"] },
{ officialName: "dispenser", synonyms: ["pump", "pump dispenser", "spray", "spray bottle"] },
{ officialName: "bulk", synonyms: ["loose", "wholesale", "kg bag", "10kg", "5kg", "20kg", "50kg"] },
{ officialName: "large", synonyms: ["big", "jumbo", "xl", "x-large", "extra large", "lge", "lg", "lrg"] },
{ officialName: "medium", synonyms: ["med", "mdm", "mid", "regular"] },
{ officialName: "small", synonyms: ["mini", "sm", "sml", "sm.", "lite", "light", "small size"] },
{ officialName: "extra large", synonyms: ["xl", "x-large", "xxl", "family size", "king size", "king-size"] },
{ officialName: "economy", synonyms: ["eco", "economy size", "value size", "value pack", "budget", "saver", "saver pack"] },
{ officialName: "double", synonyms: ["twin pack", "twin", "duo", "2 pack", "2-pack", "x2"] },
{ officialName: "triple", synonyms: ["3 pack", "3-pack", "x3", "trio"] },
{ officialName: "multipack", synonyms: ["multi pack", "multi-pack", "variety pack", "assorted", "bundle"] },
{ officialName: "half", synonyms: ["1/2", "half pack", "half size", "500ml", "500g"] },
{ officialName: "quarter", synonyms: ["1/4", "quarter pack", "250ml", "250g"] },
{ officialName: "original", synonyms: ["orig", "classic", "regular", "standard", "traditional", "plain", "unflavoured", "natural"] },
{ officialName: "natural", synonyms: ["nat", "plain", "unflavoured", "unsweetened", "pure"] },
{ officialName: "fortified", synonyms: ["fort", "enriched", "vitamins added", "with vitamins", "+ vitamins"] },
{ officialName: "low fat", synonyms: ["lo fat", "lite", "light", "reduced fat", "fat free", "fat-free", "0% fat", "skimmed", "slim"] },
{ officialName: "full cream", synonyms: ["full fat", "whole milk", "whole", "richness", "full cream milk"] },
{ officialName: "sugar free", synonyms: ["sugarfree", "sugar-free", "no sugar", "zero sugar", "0% sugar", "diet", "unsweetened"] },
{ officialName: "organic", synonyms: ["org", "bio", "natural organic", "certified organic"] },
{ officialName: "wholemeal", synonyms: ["whole meal", "whole-meal", "wholewheat", "whole wheat", "wholegrain", "whole grain", "whole-grain", "brown"] },
{ officialName: "instant", synonyms: ["inst", "quick cook", "quick-cook", "2 min", "3 min", "fast cook", "easy cook"] },
{ officialName: "concentrated", synonyms: ["conc", "concentrate", "concentrated formula"] },
{ officialName: "scented", synonyms: ["fragranced", "perfumed", "floral", "lavender", "rose", "lemon fresh"] },
{ officialName: "unscented", synonyms: ["fragrance free", "fragrance-free", "sensitive", "gentle"] },
{ officialName: "antibacterial", synonyms: ["anti bacterial", "anti-bacterial", "antibac", "germ protection", "kills germs"] },
{ officialName: "moisturising", synonyms: ["moisturizing", "moisturiser", "moisturizer", "with moisturiser", "hydrating"] },
{ officialName: "whitening", synonyms: ["whitening formula", "whitens", "brightening", "bright"] },
{ officialName: "2 in 1", synonyms: ["2in1", "2-in-1", "two in one", "combo", "dual action"] },
{ officialName: "3 in 1", synonyms: ["3in1", "3-in-1", "three in one"] },
{ officialName: "soap", synonyms: ["sabuni", "bar soap", "bathing soap", "bathing bar", "shower soap", "body wash"] },
{ officialName: "shampoo", synonyms: ["hair wash", "hair shampoo", "shamp"] },
{ officialName: "conditioner", synonyms: ["hair conditioner", "cond", "hair cond", "after shampoo"] },
{ officialName: "lotion", synonyms: ["body lotion", "moisturiser", "moisturizer", "cream", "skin lotion", "body cream"] },
{ officialName: "petroleum jelly", synonyms: ["petrol jelly", "vaseline", "jelly", "baby jelly"] },
{ officialName: "toothpaste", synonyms: ["tooth paste", "dawa ya meno", "t/paste", "dental cream", "teeth paste"] },
{ officialName: "toothbrush", synonyms: ["tooth brush", "t/brush", "dental brush", "brush"] },
{ officialName: "deodorant", synonyms: ["deo", "antiperspirant", "anti perspirant", "anti-perspirant", "roll on", "roll-on", "spray deo"] },
{ officialName: "sanitary pad", synonyms: ["pad", "pads", "sanitary towel", "sanitary napkin", "s/pad", "s/pads", "ladies pad"] },
{ officialName: "tampon", synonyms: ["tampons", "s/tampon"] },
{ officialName: "diapers", synonyms: ["nappies", "nappy", "diaper", "baby nappy", "baby diapers", "pampers"] },
{ officialName: "razor", synonyms: ["shaving razor", "blade", "shaver", "shaving blade"] },
{ officialName: "shaving cream", synonyms: ["shaving foam", "shaving gel", "s/cream", "shave cream"] },
{ officialName: "cotton wool", synonyms: ["cotton", "cotton balls", "cotton pads", "c/wool"] },
{ officialName: "tissue", synonyms: ["facial tissue", "tissues", "face tissue", "kleenex", "face wipes"] },
{ officialName: "toilet paper", synonyms: ["toilet roll", "bathroom tissue", "t/paper", "t/roll", "loo roll", "bathroom roll"] },
{ officialName: "wet wipes", synonyms: ["wipes", "baby wipes", "moist wipes", "hand wipes", "antibacterial wipes"] },
{ officialName: "sunscreen", synonyms: ["sunblock", "spf", "sun cream", "sun protection", "sunscream"] },
{ officialName: "washing powder", synonyms: ["laundry powder", "detergent", "washing detergent", "clothes washing", "w/powder"] },
{ officialName: "washing liquid", synonyms: ["laundry liquid", "liquid detergent", "washing gel", "w/liquid"] },
{ officialName: "fabric softener", synonyms: ["softener", "conditioner", "fabric conditioner", "clothes softener", "f/softener"] },
{ officialName: "bleach", synonyms: ["jik", "chlorine", "whitener", "colour remover", "bleeach"] },
{ officialName: "dishwashing liquid", synonyms: ["dish soap", "dishwash", "d/washing", "d/wash", "dish wash", "washing up liquid", "dish liquid", "sink soap"] },
{ officialName: "floor cleaner", synonyms: ["floor wash", "disinfectant", "mop cleaner", "floorwash", "f/cleaner"] },
{ officialName: "toilet cleaner", synonyms: ["toilet gel", "loo cleaner", "t/cleaner", "bathroom cleaner"] },
{ officialName: "multipurpose cleaner", synonyms: ["all purpose cleaner", "surface spray", "kitchen cleaner", "m/purpose", "multi purpose"] },
{ officialName: "disinfectant", synonyms: ["antiseptic", "sanitiser", "sanitizer", "germicide", "germ killer"] },
{ officialName: "air freshener", synonyms: ["freshener", "room spray", "deodoriser", "deodorizer", "a/freshener"] },
{ officialName: "insecticide", synonyms: ["pesticide", "mosquito spray", "doom", "insect killer", "bug spray", "pest control"] },
{ officialName: "mosquito coil", synonyms: ["coil", "mosquito coils", "mossi coil", "mos coil"] },
{ officialName: "assorted", synonyms: ["asst", "asstd", "ast", "mixed", "variety", "var"] },
{ officialName: "flavoured", synonyms: ["flavored", "flav", "flavour", "flavor"] },
{ officialName: "with", synonyms: ["w/", "w.", "+ "] },
{ officialName: "without", synonyms: ["w/o", "w.o.", "no ", "-free"] },
{ officialName: "and", synonyms: ["&", "n", "+", " + "] },
{ officialName: "pieces", synonyms: ["pcs", "pce", "pc", "pieces", "piece"] },
{ officialName: "kilogram", synonyms: ["kg", "kgs", "kilogramme", "kilo", "kilos"] },
{ officialName: "gram", synonyms: ["g", "gm", "gms", "grm", "grms"] },
{ officialName: "millilitre", synonyms: ["ml", "mls", "milliliter", "milliliters"] },
{ officialName: "litre", synonyms: ["l", "ltr", "ltrs", "lts", "liter", "liters"] },
{ officialName: "centimetre", synonyms: ["cm", "cms", "centimeter"] },
{ officialName: "count", synonyms: ["ct", "cnt", "qty", "quantity", "x", "pk"] },
{ officialName: "unga", synonyms: ["unga wa ngano", "unga wa mahindi", "unga wa sembe"] },
{ officialName: "mafuta", synonyms: ["mafuta ya kupikia", "mafuta ya kula"] },
{ officialName: "sukari", synonyms: ["sukari nguuru", "sukari nyeupe"] },
{ officialName: "chumvi", synonyms: ["chumvi ya meza", "chumvi ya bahari"] },
{ officialName: "sabuni", synonyms: ["sabuni ya mwili", "sabuni ya kuosha", "sabuni ya nguo"] },
{ officialName: "dawa", synonyms: ["dawa ya meno", "dawa ya ugonjwa"] },
{ officialName: "nyanya", synonyms: ["tomato", "nyanya mbichi"] },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function addGroup(
  endpoint: string,
  group: { officialName: string; synonyms: string[] },
): Promise<void> {
  const url = `${CONVEX_HTTP_URL}${endpoint}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(group),
  });

  if (!res.ok) {
    const text = await res.text();
    // Already exists — skip silently
    if (res.status === 500 && text.includes("already exists")) {
      console.log(`  skip  "${group.officialName}" (already exists)`);
      return;
    }
    throw new Error(`POST ${endpoint} failed (${res.status}): ${text}`);
  }

  console.log(`  added "${group.officialName}"`);
}

async function seedAll(): Promise<void> {
  console.log("\n── Seeding brand synonyms ───────────────────────────────────");
  for (const group of BRAND_GROUPS) {
    await addGroup("/synonyms/brands/add", group);
  }

  console.log("\n── Seeding word synonyms ────────────────────────────────────");
  for (const group of WORD_GROUPS) {
    await addGroup("/synonyms/words/add", group);
  }

  console.log("\nDone.\n");
}

seedAll().catch((err) => {
  console.error(err);
  process.exit(1);
});